limits:
  max_width: 320
  min_width: -64
  worlds: ['world', 'world_nether']

blocks_exclude:
  interact:
  - CRAFTING_TABLE
  farm:
  - PUPKIN_STEM
  - MELON_STEM
  break: []

blocks:
  iron:
    material: iron_block
    radius: 5

database:
  type: json
  json_file: 'regions.json'
  mysql_host: 'localhost'
  mysql_username: 'admin'
  mysql_password: 'password'
  mysql_database: 'mtblockspot'

messages:
  on_claim: '&aÁrea protegida'
  on_unclaim: '&cÁrea desprotegida'
  on_pvp: '&cO pvp foi desativado nessa área'
  on_interact: '&cEssa área está protegida!'
  error_world: '&cVocê não pode usar blocos de proteção nesse mundo!'
  error_permission: '&cVocê não tem permissão para usar esse bloco de proteção!'
  error_limit: '&cVocê atingiu seu limite de blocos de proteção de {limit}!'
  error_near: '&cExitem blocos de proteção próximos de você!'
  error_protected: '&cEssa área está protegida!'